version: '3'
services:

  backend:
    image: lubosmato/grow-backend:latest
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - sqlite:/app/db/
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - net
    depends_on:
      - mqtt
    logging:
      driver: "json-file"
      options:
        max-size: "2M"
        max-file: "10"

  frontend:
    image: lubosmato/grow-frontend:latest
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - web-root:/app/dist/
    restart: "no"
    networks:
      - net
    logging:
      driver: "json-file"
      options:
        max-size: "2M"
        max-file: "10"

  nginx:
    image: lubosmato/grow-nginx:latest
    build:
      context: ./nginx/
      dockerfile: Dockerfile
      args:
        ENABLED_MODULES: brotli
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/nginx/certs/:ro
      - web-root:/var/www/html
    networks:
      - net
    depends_on:
      - backend
      - frontend

  mqtt:
    image: lubosmato/grow-mqtt:latest
    build:
      context: ./mqtt/
      dockerfile: Dockerfile
    ports:
      - 8883:8883
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - certbot-etc:/app/certs/:ro
    networks:
      - net

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email lubos.matejcik@gmail.com --agree-tos --no-eff-email --keep-until-expiring -d grow.lubosmatejcik.cz
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  net:
    driver: bridge

volumes:
  sqlite:
    driver: local
  certbot-etc:
  certbot-var:
  web-root:
